### ISSUE TITLE
Build on Windows with MSYS2 UCRT64

### ISSUE THREAD

**Issue by ghost** [fluxer/katie#13]
Hi. I'm searching for Qt4 forks on Github and found your project. Unfortunately I'm on Windows and your project seems don't support Windows. If you could add Windows support I'm very pleased to help test building on MSYS2 UCRT64. Please consider. Thank you.

**Comment by fluxer** [comment]
Hi,

That will not happen, I do not want to support it in any way.

**Comment by fluxer** [comment]
Closing, it is also noted on the [wiki](https://github.com/fluxer/katie/wiki/Unsupported-Operating-Systems).

Cheers!
