### ISSUE TITLE
HaikuOS support

### ISSUE THREAD

**Issue by ghost** [fluxer/katie#14]
HaikuOS is not on https://github.com/fluxer/katie/wiki/Unsupported-Operating-Systems.

**Comment by fluxer** [comment]
The list includes only Operating Systems that were (somewhat) supported before the fork but eventually became unsupported, it does not include every OS out there.

**Comment by ghost** [comment]
HaikuOS has their own patched Qt4 that seems not upstreamed (I don't know for sure). What I can be sure is I used to be able to run Qt4 applications on HaikuOS. On HaikuOS now they removed Qt4 and switched to Qt5 and Qt6 already.

**Comment by fluxer** [comment]
Bottom line is the information does not concern anyone using or looking into Katie and it is not supposed to be on the list.

Regardless of what toolkit it uses it is probably still behind any of the BSDs when it comes to usability too.

**Comment by ghost** [comment]
> Regardless of what toolkit it uses it is probably still behind any of the BSDs when it comes to usability too.

Qt on HaikuOS is rather full featured. They even ported QtWebEngine and able to use QtWebEngine based web browsers like Falkon. The state of Qt on HaikuOS is even better than OpenIndiana (a distribution of illumos and thus is SunOS/Solaris and supported by your project). OpenIndiana only has an outdated version of Qt5 enough for them to run VirtualBox (the only piece of Qt5 application on their OS) as I recall, they lacked QtWebEngine and even QtWebKit. Compared to OpenIndiana, the HaikuOS devs have done an awesome job. Compared to the BSDs I think the experience with Qt on HaikuOS is on par or even better, it only limitation is since HaikuOS is an completely different OS you can't run a Qt based desktop environment like KDE on HaikuOS. But I know KDE libs built and working fine on HaikuOS, given KDE based application like Falkon is available and working on HaikuOS.

**Comment by fluxer** [comment]
Closing.
