### ISSUE TITLE
Possible to backport QtWidgets from Qt5?

### ISSUE THREAD

**Issue by barracuda156** [fluxer/katie#15]
Multiple ports require specifically QtWidgets, and this prevents from building them with Qt4 (perhaps among other issues, but this is a notable one). Is it possible to backport/implement it here?

**Comment by fluxer** [comment]
Possible probably but deffinetly not required for the purposes of Katana which [has](https://github.com/fluxer/kdelibs/tree/master/kdeui/widgets) [plenty](https://github.com/fluxer/kdelibs/blob/master/kdewidgets/kde.widgets) of widgets [some](https://github.com/fluxer/kdelibs/blob/master/kutils/kmediaplayer/kmediawidget.h) of which [I wrote myself](https://github.com/fluxer/kdelibs/commit/4de3537a821211f62d36da4917738b4cef007fcf) for particular purpose.

If porting requires widgets that are not provided by Katie or even Katana writing custom widgets to make porting easier and packing the widgets into a library would be the way to go but not as part of Katie I believe. It will be like maintaining [qt3support](https://github.com/fluxer/qt/tree/4.8/src/qt3support) module and question is how does that benefit Katie and Katana - from what I can tell the component you talk about (QtWidgets) is just stuff being moved out of the gui (or QtGui) component into other one and I am not interested in doing so just for compatibility with other project but if there is more than that to it I already explained above how to do it (port to widgets from [kdelibs](https://github.com/fluxer/kdelibs), roll your own or something else entirely).

So, are you sure such module has to be maintained as part of Katie? Who will maintained it and for what?

**Comment by barracuda156** [comment]
@fluxer Thank you for replying on this. References are helpful. I will have to look into which specifically components are required for the ports I have in mind. Will update on this in a while.

**Comment by fluxer** [comment]
Closing due to the question being answered, also I believe you also figured that what you was up to (porting Katie to unsupported platform) is a no-no.

**Comment by barracuda156** [comment]
> Closing due to the question being answered, also I believe you also figured that what you was up to (porting Katie to unsupported platform) is a no-no.

Re widgets it was answered, yes.  Re porting: no, it should be perfectly doable, just the code has to be fixed wherever currently broken. How involving is that, I cannot say yet, no time to look into that. I will return to this in a while.

**Comment by fluxer** [comment]
The code for the platform is not broken, I removed it completely.

**Comment by barracuda156** [comment]
> The code for the platform is not broken, I removed it completely.

I got it working via X11 on macOS now with absolutely minimal fixes.
